version: '3'
services:
  satisfactory-server:
      container_name: 'satisfactory-server'
      hostname: 'satisfactory-server'
      image: 'wolveix/satisfactory-server:latest'
      ports:
        - '7777:7777/tcp'
        - '7777:7777/udp'
      volumes:
          - '/etc/opt/satisfactory/data:/config'
      environment:
          - MAXPLAYERS=6
          - PGID=1000
          - PUID=1000
          - ROOTLESS=false
          - STEAMBETA=false
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 12G
          reservations:
            memory: 4G